// export interface UsageRecord {
//   id?: number; // Auto-generated by DB
//   purchase_id: CustomerPurchaseID;
//   timestamp: Date; // Use Date object for TIMESTAMPTZ
//   usage_amount: number;
//   usage_unit: string;
//   billed_amount: number;
//   description?: string;
//   metadata?: Record<string, any>; // JSONB type
// }
// vendor_billing_api_key
